### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Crystal-Spider** [styvesg/nsd_gnet8x#1]
Hello,

thank you for your repository, it is very helpful!  
I was looking at the `data_preparation` notebook and I am stuck on a missing file.  
All other files I could get from either NSD or COCO, but I'm puzzled on how to get the `nsd_to_coco_indice_map.h5py` file.  
Hoping you still look after this repo, could you please tell me where/how to get it?

Thanks in advance!

**Comment by VentusYue** [comment]
> Hello,
> 
> thank you for your repository, it is very helpful! I was looking at the `data_preparation` notebook and I am stuck on a missing file. All other files I could get from either NSD or COCO, but I'm puzzled on how to get the `nsd_to_coco_indice_map.h5py` file. Hoping you still look after this repo, could you please tell me where/how to get it?
> 
> Thanks in advance!

Hi, I meet with the same issue, do you have updates on this?

**Comment by Crystal-Spider** [comment]
Unfortunately not, in the end I just didn't crop the pictures and took a different approach.

**Comment by styvesg** [comment]
I don't rightly remember where this file was generated. However, its only use was in adapting auxiliary COCO images to the NSD cropping which, though it was referred to in one of the notebooks, was not directly used in this analysis/report.

If it can be of use, here it is: [nsd_to_coco_indice_map.zip](https://github.com/styvesg/nsd_gnet8x/files/13381938/nsd_to_coco_indice_map.zip)

P.S. Sorry I missed the OP question.

**Comment by VentusYue** [comment]
> I don't rightly remember where this file was generated. However, its only use was in adapting auxiliary COCO images to the NSD cropping which, though it was referred to in one of the notebooks, was not directly used in this analysis/report.
> 
> If it can be of use, here it is: [nsd_to_coco_indice_map.zip](https://github.com/styvesg/nsd_gnet8x/files/13381938/nsd_to_coco_indice_map.zip)
> 
> P.S. Sorry I missed the OP question.

Thank you! It is greatly appreciated!
